<a href="https://colab.research.google.com/github/danilot1/intensivo-python/blob/main/C%C3%B3pia_de_Aula_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Defina uma função que recebe o nome do usuário, e imprime a mensagem na tela: “Olá, xxxx. Seja bem vindo”;

In [ ]:
def nome_do_usuario():
  nome = input("Digite seu nome ")
  print ("Olá,",nome,"Seja bem vindo")
nome_do_usuario()

Digite seu nome danilo
Olá, danilo Seja bem vindo


Implemente uma função que receba como argumentos dois valores que o usuário informar, e retorne e a soma dos dois valores

In [8]:

def calculo(num1,num2): 
  return num1 + num2
resultado = calculo(3,3)
print(resultado)

  

6


Implemente uma função que recebe um número, e retorna se esse número é par ou não.  Use a lista numeros = [ 12, 356, 98,  89, 45, 12, 90, 34, 123, 834, 979 ] para fazer o uso da função

In [14]:
def function():
  lista = [12, 356, 98, 89, 45, 12, 90, 34, 123, 834, 979]
  for x in lista:
    if x % 2 == 0:
      print(x,"é par")
    else:
      print(x,'é ímpar')
function()     

12 é par
356 é par
98 é par
89 é ímpar
45 é ímpar
12 é par
90 é par
34 é par
123 é ímpar
834 é par
979 é ímpar


Faça uma função que receba a altura e o peso de um estudante e calcule e retorne seu IMC

In [2]:
def funcao():
  altura = float(input("Digite sua altura: "))
  peso = float(input("Digite seu peso: "))
  IMC = float(peso/(altura*altura))
  return "o seu imc é", IMC
funcao()


Digite sua altura: 1.85
Digite seu peso: 86.0


('o seu imc é', 25.127830533235937)

Faça uma função que recebe dois números informados pelo usuário e imprime na tela qual é o maior do dois

In [ ]:
def verify():
  num1 = int(input("Digite seu numero: "))
  num2 = int(input("Digite seu numero "))
  if num1 > num2:
    print("O numero maior é",num1)
  else:
    print("O numero maior é",num2)
verify()

Digite seu numero: 0
Digite seu numero 1
O numero maior é 1


Faça uma função que receba uma lista de números n_lista= [ 12, 356, 98,  89, 45, 12, 90, 34, 123, 834, 979 ] e retorne  a média desses números

In [ ]:
def funcao():
  n_lista = [12, 356, 98, 89, 45, 12, 90, 34, 123, 834, 979 ]
  soma_lista = sum(n_lista)
  media = soma_lista/11
  return media
funcao()

242.9090909090909

Faça uma função que receba a lista acima e retorne o menor número

In [ ]:
def funcao():
  n_lista = [12, 356, 98, 89, 45, 12, 90, 34, 123, 834, 979 ]
  return n_lista[5]
funcao()  

Faça uma função que use a lista acima e retorne o maior número

In [ ]:
def funcao():
  n_lista = [12, 356, 98, 89, 45, 12, 90, 34, 123, 834, 979 ]
  return n_lista[10]
funcao()  

979

Crie uma função para deixar um nome somente com as iniciais maiúsculas, independente de como o usuário informar o nome. Receba o nome e use a função para formatá-lo

In [ ]:
def funcao():
  nome = input("Digite seu nome: ")
  print(nome.title())
funcao()

Digite seu nome: danilo teixeira
Danilo Teixeira


Faça uma função que recebe uma lista de números e exclui da lista apenas os números pares

In [ ]:
def funcao():
  lista = []
  for x in range(0,10):
    numero = int(input("Digite seu número: "))
    lista.append(numero)
    if lista[x] % 2 == 0:
      del lista[x]
      return lista
funcao()

Digite seu número: 1
Digite seu número: 5
Digite seu número: 7
Digite seu número: 13
Digite seu número: 2


[1, 5, 7, 13]

Faça uma função que recebe a média final de um aluno por parâmetro e retorna o seu conceito, conforme a tabela abaixo:


Nota Conceito de 0,0 a 4,9 D
de 5,0 a 6,9 C
de 7,0 a 8,9 B
de 9,0 a 10,0 A



In [ ]:
def funcao():
  media_final = float(input("Digite a sua média final: "))
  if media_final >= 0.0 and media_final <= 4.9:
    print("Nota conceito D")
  elif media_final >= 5.0 and media_final <= 6.9:
    print("Nota conceito C")
  elif media_final >= 7.0 and media_final <= 8.9:
    print("Nota conceito B")
  elif media_final >= 9.0 and media_final <= 10.0:
    print("Nota conceito A")
funcao()


Digite a sua média final: 6.7
Nota conceito C


Faça uma função que recebe o diâmetro de uma circunferência e retorna a sua área; Use a expressão A = 2𝝅r², Onde A é a área, 𝝅=3,14, e r é o raio da circunferência, lembrando que r é igual ao diâmetro/2

In [ ]:
def funcao():
  diametro = float(input("Digite o diametro: "))
  raio = diametro/2
  pi = 3.14
  area = 2 *pi*(raio*raio)
  return area
funcao()

Digite o diametro: 5


39.25

Faça uma função que calcula o valor de uma corrida de Uber. Essa função recebe como argumento a distância a ser percorrida. E calcula da seguinte forma: 5,75 fixo, mais 3,25 por quilômetro. Então solicite a distância da corrida e retorne o valor da corrida, com uma mensagem amigável

In [17]:
def funcao(distancia):
  preco_por_km = 3.25
  valor = 5.75 + (distancia * preco_por_km)
  return "Caro passageiro o valor da sua corrida foi", valor
distancia = int(input("Informe a distância da sua corrida"))
funcao(distancia)

Informe a distância da sua corrida20


('Caro passageiro o valor da sua corrida foi', 70.75)

Crie uma função que recebe uma string e  valida o login do usuário, verificar se o nome contém apenas caracteres alfabéticos e possui menos que 30 caracteres, e outra função que recebe uma senha e valida se a senha possui apenas caracteres alfanuméricos. 

In [24]:
def function():
  login = input("Digite seu nome :")
  print ("O valor {} é alfábetico ? {}".format(login, login.isalpha()))
  return login.count(login)
function()
def function2():
  senha = input("Digite sua senha :")
  print ("A senha {} é alfanumerica ? {} ".format(senha, senha.isalnum()))
function2()


Digite seu nome :Danilo
O valor Danilo é alfábetico ? True
Digite sua senha :Bola123
A senha Bola123 é alfanumerica ? True 


Crie uma função validar_usuario(login, senha) que retorne True se o login e senha forem validados e False se algum não passa na validação. Imprima na tela se o “usuário e senha foram cadastrados com sucesso” ou “Há algum dado inválido”

Vamos fazer uma calculadora simples. Faça uma função chamada operacao_aritmetica( ) que recebe 3 argumentos. Um número, outro número e um sinal aritmético (+, -, / ou *). Então solicite ao usuário os valores de entrada e chame a função operacao_aritmetica( ) , passe seus argumentos e imprima na tela o nome da operação e o resultado. Valide também se o usuário informou um operador inválido, quer dizer diferente de um dos  4 válidos (+, -, / ou *)