<a href="https://colab.research.google.com/github/danilot1/intensivo-python/blob/main/C%C3%B3pia_de_Aula_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ATIVIDADE DE OPERAÇÕES COM CONJUNTOS


Crie um conjunto com os números de 1 a 10

In [ ]:
conjunto = {1 , 2, 3, 4 , 5, 6, 7, 8, 9, 10}
print(conjunto)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


Use a função “set( )” para criar um conjunto com 10 letra do alfabeto

In [ ]:
conjunto = set("abcdefghij")
print(conjunto)

{'e', 'g', 'j', 'c', 'a', 'd', 'h', 'f', 'i', 'b'}


Crie um conjunto com os seguintes elementos “abfsdabfgasedass”, e em seguida imprima o tamanho do conjunto com uma mensagem amigável. Abaixe explique o porque do conjunto ter o tamanho informado por você e não 16

In [ ]:
conjunto = set("abfsdabfgasedass")
print("o tamanho do conjunto é", len(conjunto))
#devido a funcao len contar a nomeação do conjunto e não o elemento contido nele

o tamanho do conjunto é 7


Realize a operação de união com os conjuntos a = {123456} e b={456789} e atribua a um conjunto ‘c’. Mostre na tela o conjunto formado e tamanho de cada conjunto individualmente, além do tamanho do conjunto ‘c’

In [ ]:
a = {123456}
b={456789}
c = set(a|b)
print(c)
print(len(a), len(b),len(c))


{123456, 456789}
1 1 2


Realize a operação de intersecção com os conjuntos a = {123456} e b={456789} e atribua a um conjunto ‘c’. Mostre na tela o conjunto formado e tamanho de cada conjunto individualmente, além do tamanho do conjunto ‘c’

In [ ]:
a = {123456}
b={456789}
c = set(a&b)
print(c)
print(len(a), len(b),len(c))

set()
1 1 0


Realize a operação de diferença com os conjuntos a = {123456} e b={456789} e atribua a um conjunto ‘c’. Mostre na tela o conjunto formado e tamanho de cada conjunto individualmente, além do tamanho do conjunto ‘c’

In [ ]:
a = {123456}
b={456789}
c = set(a-b)
print(c)
print(len(a), len(b),len(c))

Vamos criar um jogo. Armazene seu nome completo em uma variável. Em seguida crie uma estrutura “while” que será executada enquanto o número de acertos do usuário for menor que 3. Dentro do “while” peça para o usuário informar uma letra, e verifique, usando a notação “in” do python, se essa letra está contida no seu nome, caso positivo adicione um ponto ao usuário, no final quando ele atingir 3 pontos encerre o loop

Adicione o elemento 3 ao conjunto s={2,1,5,8,9,3,4,0} e verifique o tamanho antes e depois da inserção; Diga o que mudou depois da inserção

In [ ]:
s = {2,1,5,8,9,3,4,0}
print(len(s))
s.add(3)
print(len(s))

8
8


Crie um laço de repetição para imprimir todos os elementos do conjunto acima

In [ ]:
s = {2,1,5,8,9,3,4,0}
for x in s:
  print(s)


{0, 1, 2, 3, 4, 5, 8, 9}
{0, 1, 2, 3, 4, 5, 8, 9}
{0, 1, 2, 3, 4, 5, 8, 9}
{0, 1, 2, 3, 4, 5, 8, 9}
{0, 1, 2, 3, 4, 5, 8, 9}
{0, 1, 2, 3, 4, 5, 8, 9}
{0, 1, 2, 3, 4, 5, 8, 9}
{0, 1, 2, 3, 4, 5, 8, 9}


Com um laço, remova todos os elementos pares do conjunto acima

In [ ]:
s = {2,1,5,8,9,3,4,0}
if s % 2 ==0:
  s.discard(s)


# ATIVIDADE DE OPERAÇÕES COM DICIONÁRIOS

Crie um dicionário em vazio

In [ ]:
dicionario = {}

Crie um dicionário em que a chave seja um id de valor inteiro, e o valor seja o nome do usuário

In [ ]:
dicionario = { "id" : 1250 }
print(dicionario)

{'id': 1250}


Crie um dicionário. crie a estrutura que descreva uma loja de um shopping center

In [ ]:
dicionario = { 
    "nome" : "Lojas Americanas",
    "localização" : "primeiro andar",
}

Dado o dicionário d = {123: “nome do cliente, “fone”: 999999999, “email”: “email@email.com” }, user o comando printo para imprimir cada dado desse cliente, um em cada linha

In [ ]:
d = {
  "nome do clinte" : "José",
  "telefone" : "980028922",
  "email" : "jose@hotmail.com"  
}
print(d)

{'nome do clinte': 'José', 'telefone': '980028922', 'email': 'jose@hotmail.com'}


Crie um dicionário vazio, em seguida desenvolva a estrutura para descrever uma lista de usuário com seu “id” e seu login. Sendo “id” a chave um número inteiro. Crie 5 usuários

In [ ]:
d = {}
 

Use o método get() para recuperar o nome de um cliente a partir do valor de sua chave

In [ ]:
d = {
    "nome" : "ivan",
}
nome = d.get("nome")
print(nome)

ivan


Dados os dicionários pessoa = {“nome”: “jose”, “telefone”: 990099112233} e endereco = {“rua”: “um”, “numero”: 10, “estado”: “PE”}, una esses todos os dados apenas no dicionário pessoa

In [ ]:
pessoa = {"nome": "jose", "telefone": 990099112233}
endereço = {"rua" : "um", "numero": 10, "estado": "PE"}
endereço in pessoa
print(pessoa)

Dado o dicionário empresas = {1: “sadia”, 2: "perdigão", 3: “seara”, 4: “unilever”, 5: “ambev”}, faça um laço que mostre o par chave e valor de cada uma

Crie um dicionário que represente as características de uma pessoa

In [ ]:
pessoa = {
    "nome" : "Ismael",
    "altura" : 1.88,
    "peso" : 80.0,
    "cabelo" : "Preto"
    
}

Crie um dicionário que represente um vídeo postado no YouTube